agent:
  one:
    name: COUNTRY_low_pfr
    metric_class: proportional_item
    compatibility_class: context_compatibility
    preference_function_class: cascade_preference
    metric:
      feature: COUNTRY_low_pfr
      proportion: 0.15
    preference:
      feature: COUNTRY_low_pfr
      delta: 0.1
  two:
    name: loan_buck_5
    metric_class: proportional_item
    compatibility_class: context_compatibility
    preference_function_class: cascade_preference
    metric:
      feature: loan_buck_5
      proportion: 0.15
    preference:
      feature: loan_buck_5
      delta: 0.1
allocation:
  allocation_class: weighted_product_allocation
  properties:
    compatibility_exponent: 2
    fairness_exponent: 1
choice:
  choice_class: whalrus_scoring
  properties:
    whalrus_rule: RuleCopeland
    tie_breaker: Random
    ignore_weights: false
    recommender_weight: 0.8
context:
  context_class: csv_context
  properties:
    compatibility_file: kiva_compat_dynamic.csv
data:
  rec_filename: kiva_recs.csv
  feature_filename: kiva_item.csv
feature:
  one:
    name: COUNTRY_low_pfr
    protected_feature: COUNTRY_low_pfr
    protected_values:
    - 1
  two:
    name: loan_buck_5
    protected_feature: loan_buck_5
    protected_values:
    - 1
post:
  postprocess_class: exposure
  properties:
    filename: history.csv
    threshold: none
    binary: 'false'
location:
  path: data
  overwrite: 'true'
output:
  filename: history.json
parameters:
  list_size: 10
  iterations: -1
  initialize: skip
  history_window_size: 100
