# Sample configuration file for SCRUF-D
# For format reference only -- may not actually work in any given SCRUF-D version / data set

[location]
path = "."
overwrite = "true"

[data]
rec_filename = "recommendations.csv"
feature_filename = "item_features.csv"

[output]
filename = "history_file.json"

[parameters]
list_size = 2
iterations = -1 # -1 means run through all the users
initialize = "skip"
history_window_size = 50

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "compat_data.csv"

[feature]

[feature.f1]
name = "Feature 1"
protected_feature = "feature1"
protected_values = ["a", "b"]

[feature.f2]
name = "Feature 2"
protected_feature = "feature2"
protected_values = 1

[agent]

[agent.f1]
name = "Feature 1 Agent"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "zero_preference"

[agent.f1.metric]
feature = "Feature 1"
proportion = 0.75

[agent.f2]
name = "Feature 2 Agent"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.f2.metric]
feature = "Feature 2"
proportion = 0.5

[agent.f2.preference]
feature = "Feature 2"
delta = 0.5

[allocation]
algorithm = "weighted_product_allocation"

[allocation.properties]
fairness_exponent = 1.0
compatibility_exponent = 0.7

[choice]
algorithm = "fixed_utility"

[choice.properties]
delta = 0.5
alpha = 0.2
