# Sample configuration file for SCRUF-D
# For format reference only -- may not actually work in any given SCRUF-D version / data set

[location]
path = "your_path/here"
overwrite = "true"

[data]
rec_filename = "recommendations.txt"
feature_filename = "item_features.txt"

[output]
filename = "history_file.json"

[parameters]
list_size = 10
iterations = -1 # -1 means run through all the users
initialize = "skip"
history_window_size = 50

[feature]

[feature.country]
name = "Country"
protected_feature = "country"
protected_values = ["ug", "th", "ke", "ha"]

[feature.sector]
name = "Sector"
protected_feature = "sector"
protected_values = [7, 18, 35]

[feature.loan_size]
name = "Loan Size"
protected_feature = "bucket5"
protected_values = [1]

[agent]

[agent.country]
name = "Country"
metric_class = "proportional_fair"
compatibility = "entropy"

[agent.country.metric]
feature = "Country"

[agent.sector]
name = "Sector"
metric_class = "list_exposure"
compatibility_class = "entropy"

[agent.sector.metric]
feature = "Sector"

[agent.loan_size]
name = "Loan Size"
metric_class = "list_exposure"
compatibility_class = "risk_aversion"

[agent.loan_size.metric]
feature = "Loan Size"

[allocation]
algorithm = "weighted_product_allocation"

[allocation.properties]
fairness_exponent = 1.0
compatibility_exponent = 0.7

[choice]
algorithm = "fixed_utility"
delta = 0.5
alpha = 0.2
